version: '3'

volumes:
  rails_study_db_volume:
    driver: 'local'

  rails_study_mysql_db_volume:
    driver: 'local'

  rails_study_gem_volume:
    driver: 'local'

services:
  rails_study_front:
    build: ../../front/
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ../../front/scripts:/var/scripts
    environment:
      APP_HOST:
      APP_PORT:
    container_name: "rails_study_front"
    command: /var/scripts/start.sh

  rails_study_db:
    build: ../../db/mariadb
    volumes:
      - rails_study_db_volume:/var/lib/mysql
      - ../../db/mariadb/scripts:/var/scripts
    environment:
      DB_NAME:
      DB_HOST:
      DB_USER:
      DB_PASS:
      DB_PORT:
      MYSQL_ROOT_PASSWORD: 12345678
    container_name: "rails_study_db"
    ports:
      - "3306:3306"

  rails_study_mysql_db:
    build: ../../db/mysql
    volumes:
      - rails_study_mysql_db_volume:/var/lib/mysql
      - ../../db/mysql/scripts:/var/scripts
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DB_NAME:
      MYSQL_DB_HOST:
      MYSQL_DB_USER:
      MYSQL_DB_PASS:
      MYSQL_DB_PORT:
      MYSQL_ROOT_PASSWORD: 12345678
    container_name: "rails_study_mysql_db"
    ports:
      - "3307:3306"

  rails_study_web:
    build: ../../web/
    volumes:
      - ../../web/myapp:/myapp
      - ../../web/scripts:/var/scripts
      - rails_study_gem_volume:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DB_NAME:
      DB_HOST:
      DB_USER:
      DB_PASS:
      DB_PORT:
      MYSQL_DB_NAME:
      MYSQL_DB_HOST:
      MYSQL_DB_USER:
      MYSQL_DB_PASS:
      MYSQL_DB_PORT:
      BUNDLE_APP_CONFIG: /myapp/.bundle
      RAILS_PRODUCTION_MODE:
    container_name: "rails_study_web"
    command: /var/scripts/start_webapp.sh
