version: '2'

services:
  ruby:
    build: ./ruby
    container_name: rb
    volumes:
      - ./ruby/work:/work
    tty: true

  python:
    build: ./python
    container_name: py
    volumes:
      - ./python/work:/work
    tty: true

  go:
    build: ./golang
    container_name: go
    volumes:
      - ./golang/work/:/work
    tty: true

  elixir:
    build: ./elixir
    container_name: elixir
    volumes:
      - ./elixir/work/:/work
    tty: true

  rust:
    build: ./rust
    container_name: rust
    volumes:
      - ./rust/work/:/work
    tty: true

