version: '3.2'

volumes:
  mysql-data:
    driver: 'local'

services:
  web:
    build: ./app
    ports:
      - "4000:4000"
    command: mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - ./app:/app
    container_name: "phx_web"
    links:
      - db

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 13306:3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/work:/work
    container_name: "phx_db"